export const Productos = [
	{
		id: 1,
		nombre: "Comida para Perro Adulto",
		descripcion: "Alimento balanceado para perros adultos de todas las razas.",
		precio: 8500,
		imagen: "comida_perro_adulto.jpg",
		categoria: "Alimentos",
	},
	{
		id: 2,
		nombre: "Comida para Gato Adulto",
		descripcion: "Alimento nutritivo para gatos adultos, con sabor a pollo.",
		precio: 7800,
		imagen: "comida_gato_adulto.jpg",
		categoria: "Alimentos",
	},
	{
		id: 3,
		nombre: "Juguete para Perro Mordedor",
		descripcion: "Juguete resistente para perros, ideal para morder y jugar.",
		precio: 3200,
		imagen: "juguete_perro_mordedor.jpg",
		categoria: "Juguetes",
	},
	{
		id: 4,
		nombre: "Rascador para Gato",
		descripcion: "Rascador de cartón para gatos, ayuda a mantener sus uñas.",
		precio: 4500,
		imagen: "rascador_gato.jpg",
		categoria: "Juguetes",
	},
	{
		id: 5,
		nombre: "Correa Retráctil para Perro",
		descripcion:
			"Correa retráctil de 5 metros para perros pequeños y medianos.",
		precio: 6000,
		imagen: "correa_retractil_perro.jpg",
		categoria: "Accesorios",
	},
	{
		id: 6,
		nombre: "Collar para Gato con Cascabel",
		descripcion: "Collar ajustable para gatos, incluye un pequeño cascabel.",
		precio: 1500,
		imagen: "collar_gato.jpg",
		categoria: "Accesorios",
	},
	{
		id: 7,
		nombre: "Shampoo para Perro Hipoalergénico",
		descripcion:
			"Shampoo suave y hipoalergénico para perros con piel sensible.",
		precio: 5200,
		imagen: "shampoo_perro.jpg",
		categoria: "Higiene",
	},
	{
		id: 8,
		nombre: "Arena para Gatos Aglomerante",
		descripcion:
			"Arena aglomerante para gatos, controla olores y es fácil de limpiar.",
		precio: 3000,
		imagen: "arena_gatos.jpg",
		categoria: "Higiene",
	},
	{
		id: 9,
		nombre: "Vitaminas para Perros",
		descripcion:
			"Suplemento vitamínico para mejorar la salud y el pelaje de los perros.",
		precio: 5500,
		imagen: "vitaminas_perros.jpg",
		categoria: "Salud",
	},
	{
		id: 10,
		nombre: "Antipulgas para Gatos",
		descripcion: "Tratamiento antipulgas para gatos, protege durante 3 meses.",
		precio: 7200,
		imagen: "antipulgas_gatos.jpg",
		categoria: "Salud",
	},
	{
		id: 11,
		nombre: "Comida para Cachorros",
		descripcion: "Alimento especial para cachorros en crecimiento.",
		precio: 6400,
		imagen: "comida_cachorros.jpg",
		categoria: "Alimentos",
	},
	{
		id: 12,
		nombre: "Comida para Gatos Senior",
		descripcion: "Alimento para gatos mayores de 7 años, fácil de digerir.",
		precio: 9000,
		imagen: "comida_gatos_senior.jpg",
		categoria: "Alimentos",
	},
	{
		id: 13,
		nombre: "Pelota de Goma para Perro",
		descripcion: "Pelota de goma duradera, ideal para jugar al aire libre.",
		precio: 2800,
		imagen: "pelota_goma_perro.jpg",
		categoria: "Juguetes",
	},
	{
		id: 14,
		nombre: "Ratón de Juguete para Gato",
		descripcion:
			"Ratón de peluche con catnip, para estimular el juego de los gatos.",
		precio: 2000,
		imagen: "raton_juguete_gato.jpg",
		categoria: "Juguetes",
	},
	{
		id: 15,
		nombre: "Transportadora para Perros y Gatos",
		descripcion: "Transportadora segura y cómoda para viajes.",
		precio: 9800,
		imagen: "transportadora.jpg",
		categoria: "Accesorios",
	},
];
