export const Productos = [
	{
		id: 1001,
		nombre: "Comida para Perro Adulto",
		descripcion:
			"Alimento completo para perros adultos. Rico en proteínas y fibras. Mejora la salud digestiva y el brillo del pelaje. Presentación en bolsa de 2 kg. Sabor a pollo y arroz.",
		precio: 15000,
		imagen: "https://via.placeholder.com/150?text=Comida+Perro+Adulto",
		categoria: "Alimentos",
		stock: 50,
		tags: ["perro", "adulto", "comida", "proteínas", "fibras"],
	},
	{
		id: 1002,
		nombre: "Arena para Gatos",
		descripcion:
			"Arena sanitaria para gatos. Alta absorción y control de olores. No produce polvo. Presentación en bolsa de 10 kg. Ideal para hogares con varios gatos.",
		precio: 12000,
		imagen: "https://via.placeholder.com/150?text=Arena+Gatos",
		categoria: "Higiene",
		stock: 30,
		tags: ["gato", "arena", "sanitaria", "absorción", "control de olores"],
	},
	{
		id: 1003,
		nombre: "Juguete para Perro en Forma de Hueso",
		descripcion:
			"Juguete resistente para perros en forma de hueso. Ideal para masticar y jugar. Fabricado con materiales no tóxicos. Ayuda a mantener los dientes limpios. Disponible en varios tamaños.",
		precio: 8000,
		imagen: "https://via.placeholder.com/150?text=Juguete+Perro+Hueso",
		categoria: "Juguetes",
		stock: 20,
		tags: ["perro", "juguete", "hueso", "resistente", "masticar"],
	},
	{
		id: 1004,
		nombre: "Collar para Gato Reflectante",
		descripcion:
			"Collar reflectante para gatos. Aumenta la visibilidad en la oscuridad. Ajustable y cómodo. Incluye una campanilla. Disponible en varios colores.",
		precio: 7000,
		imagen: "https://via.placeholder.com/150?text=Collar+Gato+Reflectante",
		categoria: "Accesorios",
		stock: 40,
		tags: ["gato", "collar", "reflectante", "visibilidad", "ajustable"],
	},
	{
		id: 1005,
		nombre: "Jaula para Conejos",
		descripcion:
			"Jaula espaciosa para conejos. Incluye bebedero y comedero. Fácil de limpiar y desmontar. Fabricada con materiales resistentes. Ideal para interior y exterior.",
		precio: 18000,
		imagen: "https://via.placeholder.com/150?text=Jaula+Conejos",
		categoria: "Hábitats",
		stock: 15,
		tags: ["conejo", "jaula", "espaciosa", "resistente", "fácil de limpiar"],
	},
	{
		id: 1006,
		nombre: "Vitaminas para Perros",
		descripcion:
			"Suplemento vitamínico para perros. Mejora la salud general y el sistema inmunológico. Presentación en tabletas masticables. Apto para todas las edades y razas.",
		precio: 10000,
		imagen: "https://via.placeholder.com/150?text=Vitaminas+Perros",
		categoria: "Medicamentos",
		stock: 60,
		tags: ["perro", "vitaminas", "suplemento", "salud", "inmunológico"],
	},
	{
		id: 1007,
		nombre: "Comida para Gato Adulto",
		descripcion:
			"Alimento completo para gatos adultos. Rico en proteínas y taurina. Mejora la salud cardiovascular y ocular. Presentación en bolsa de 1.5 kg. Sabor a salmón y arroz.",
		precio: 14000,
		imagen: "https://via.placeholder.com/150?text=Comida+Gato+Adulto",
		categoria: "Alimentos",
		stock: 45,
		tags: ["gato", "adulto", "comida", "proteínas", "taurina"],
	},
	{
		id: 1008,
		nombre: "Shampoo para Perros",
		descripcion:
			"Shampoo suave para perros. Limpia y desodoriza el pelaje. Fórmula hipoalergénica. Presentación en botella de 500 ml. Ideal para perros con piel sensible.",
		precio: 6000,
		imagen: "https://via.placeholder.com/150?text=Shampoo+Perros",
		categoria: "Higiene",
		stock: 35,
		tags: ["perro", "shampoo", "suave", "desodoriza", "hipoalergénico"],
	},
	{
		id: 1009,
		nombre: "Juguete para Gato en Forma de Ratón",
		descripcion:
			"Juguete interactivo para gatos en forma de ratón. Estimula el instinto de caza. Fabricado con materiales no tóxicos. Ideal para mantener a los gatos activos y entretenidos.",
		precio: 5000,
		imagen: "https://via.placeholder.com/150?text=Juguete+Gato+Raton",
		categoria: "Juguetes",
		stock: 25,
		tags: ["gato", "juguete", "ratón", "interactivo", "caza"],
	},
	{
		id: 1010,
		nombre: "Cama para Perro Mediana",
		descripcion:
			"Cama cómoda para perros medianos. Material suave y lavable. Diseño ergonómico que proporciona apoyo y comodidad. Disponible en varios colores.",
		precio: 20000,
		imagen: "https://via.placeholder.com/150?text=Cama+Perro+Mediana",
		categoria: "Accesorios",
		stock: 10,
		tags: ["perro", "cama", "mediana", "suave", "ergonómica"],
	},
	{
		id: 1011,
		nombre: "Terrario para Reptiles",
		descripcion:
			"Terrario de vidrio para reptiles. Incluye sistema de ventilación y calefacción. Fácil de limpiar. Tamaño ideal para lagartos y serpientes pequeñas.",
		precio: 20000,
		imagen: "https://via.placeholder.com/150?text=Terrario+Reptiles",
		categoria: "Hábitats",
		stock: 5,
		tags: ["reptiles", "terrario", "vidrio", "ventilación", "calefacción"],
	},
	{
		id: 1012,
		nombre: "Antiparasitario para Perros",
		descripcion:
			"Antiparasitario interno y externo para perros. Eficaz contra pulgas, garrapatas y parásitos intestinales. Presentación en pipetas. Fácil de aplicar.",
		precio: 13000,
		imagen: "https://via.placeholder.com/150?text=Antiparasitario+Perros",
		categoria: "Medicamentos",
		stock: 50,
		tags: ["perro", "antiparasitario", "pulgas", "garrapatas", "pipetas"],
	},
	{
		id: 1013,
		nombre: "Comida para Gato Kitten",
		descripcion:
			"Alimento completo para gatitos. Rico en proteínas y DHA. Promueve el crecimiento saludable y el desarrollo cerebral. Presentación en bolsa de 1 kg. Sabor a pollo y pescado.",
		precio: 12000,
		imagen: "https://via.placeholder.com/150?text=Comida+Gato+Kitten",
		categoria: "Alimentos",
		stock: 55,
		tags: ["gato", "kitten", "comida", "proteínas", "DHA"],
	},
	{
		id: 1014,
		nombre: "Juguete para Perro en Forma de Pelota",
		descripcion:
			"Pelota de goma para perros. Ideal para juegos de buscar y masticar. Resistente y duradera. Disponible en varios colores y tamaños.",
		precio: 7000,
		imagen: "https://via.placeholder.com/150?text=Juguete+Perro+Pelota",
		categoria: "Juguetes",
		stock: 30,
		tags: ["perro", "juguete", "pelota", "goma", "resistente"],
	},
	{
		id: 1015,
		nombre: "Cucha para Perro Grande",
		descripcion:
			"Cucha resistente para perros grandes. Material impermeable y fácil de limpiar. Diseño con protección contra el frío. Ideal para uso exterior.",
		precio: 30000,
		imagen: "https://via.placeholder.com/150?text=Cucha+Perro+Grande",
		categoria: "Accesorios",
		stock: 10,
		tags: ["perro", "cucha", "grande", "resistente", "impermeable"],
	},
	{
		id: 1016,
		nombre: "Kit de Cepillos para Perro",
		descripcion:
			"Kit de cepillos para el cuidado del pelaje del perro. Incluye cepillo de cerdas y carda. Ideal para desenredar y eliminar pelos sueltos. Adecuado para todas las razas.",
		precio: 9000,
		imagen: "https://via.placeholder.com/150?text=Kit+Cepillos+Perro",
		categoria: "Higiene",
		stock: 40,
		tags: ["perro", "cepillos", "cuidado", "pelaje", "desenredar"],
	},
	{
		id: 1017,
		nombre: "Caja de Transporte para Gato",
		descripcion:
			"Caja de transporte segura para gatos. Material resistente y fácil de limpiar. Incluye puerta de malla y asa para transporte. Ideal para visitas al veterinario.",
		precio: 15000,
		imagen: "https://via.placeholder.com/150?text=Caja+Transporte+Gato",
		categoria: "Accesorios",
		stock: 20,
		tags: ["gato", "caja", "transporte", "resistente", "malla"],
	},
	{
		id: 1018,
		nombre: "Comida para Perro Cachorro",
		descripcion:
			"Alimento especializado para cachorros. Rico en nutrientes esenciales para el crecimiento. Presentación en bolsa de 1.5 kg. Sabor a cordero y arroz.",
		precio: 14000,
		imagen: "https://via.placeholder.com/150?text=Comida+Perro+Cachorro",
		categoria: "Alimentos",
		stock: 50,
		tags: ["perro", "cachorro", "comida", "nutrientes", "cordero"],
	},
	{
		id: 1019,
		nombre: "Manta para Gato",
		descripcion:
			"Manta suave y cálida para gatos. Ideal para colocar en camas o lugares de descanso. Lavable y duradera. Disponible en varios colores y tamaños.",
		precio: 8000,
		imagen: "https://via.placeholder.com/150?text=Manta+Gato",
		categoria: "Accesorios",
		stock: 25,
		tags: ["gato", "manta", "suave", "cálida", "lavable"],
	},
	{
		id: 1020,
		nombre: "Cinturón de Seguridad para Perro",
		descripcion:
			"Cinturón de seguridad para perros para uso en el automóvil. Ajustable y fácil de instalar. Compatible con la mayoría de los vehículos. Mantiene al perro seguro durante el viaje.",
		precio: 9000,
		imagen: "https://via.placeholder.com/150?text=Cinturon+Seguridad+Perro",
		categoria: "Accesorios",
		stock: 30,
		tags: ["perro", "cinturón", "seguridad", "automóvil", "ajustable"],
	},
	{
		id: 1021,
		nombre: "Lámpara UV para Reptiles",
		descripcion:
			"Lámpara UV especializada para reptiles. Proporciona luz UVB esencial para el metabolismo del calcio. Aumenta el bienestar y la actividad de los reptiles. Vida útil de aproximadamente 6 meses.",
		precio: 11000,
		imagen: "https://via.placeholder.com/150?text=Lámpara+UV+Reptiles",
		categoria: "Hábitats",
		stock: 20,
		tags: ["reptiles", "lámpara", "UV", "UVB", "bienestar"],
	},
	{
		id: 1022,
		nombre: "Piñata para Perro",
		descripcion:
			"Piñata interactiva para perros. Llena de premios y golosinas. Estimula la mente y el cuerpo del perro. Fabricada con materiales resistentes y seguros.",
		precio: 10000,
		imagen: "https://via.placeholder.com/150?text=Pinata+Perro",
		categoria: "Juguetes",
		stock: 15,
		tags: ["perro", "piñata", "interactiva", "premios", "resistente"],
	},
	{
		id: 1023,
		nombre: "Cepillo Deslanador para Gato",
		descripcion:
			"Cepillo deslanador para gatos. Elimina pelos sueltos y enredos. Ideal para gatos de pelo largo. Fácil de usar y limpiar.",
		precio: 8500,
		imagen: "https://via.placeholder.com/150?text=Cepillo+Deslanador+Gato",
		categoria: "Higiene",
		stock: 40,
		tags: ["gato", "cepillo", "deslanador", "pelaje largo", "fácil de limpiar"],
	},
	{
		id: 1024,
		nombre: "Alimento para Conejos Adultos",
		descripcion:
			"Comida balanceada para conejos adultos. Rica en fibras y nutrientes esenciales. Presentación en bolsa de 2 kg. Ideal para mantener una buena salud digestiva.",
		precio: 13000,
		imagen: "https://via.placeholder.com/150?text=Alimento+Conejos+Adultos",
		categoria: "Alimentos",
		stock: 25,
		tags: ["conejo", "adulto", "comida", "fibra", "nutrientes"],
	},
	{
		id: 1025,
		nombre: "Rascador para Gato",
		descripcion:
			"Rascador para gatos con base resistente. Ideal para mantener las uñas del gato afiladas y evitar que rasque los muebles. Incluye postes y superficies de sisal.",
		precio: 25000,
		imagen: "https://via.placeholder.com/150?text=Rascador+Gato",
		categoria: "Accesorios",
		stock: 20,
		tags: ["gato", "rascador", "nails", "muebles", "sisal"],
	},
	{
		id: 1026,
		nombre: "Suplemento de Calcio para Perros",
		descripcion:
			"Suplemento de calcio para perros. Ayuda a fortalecer huesos y dientes. Presentación en tabletas. Apto para perros de todas las edades.",
		precio: 10000,
		imagen: "https://via.placeholder.com/150?text=Suplemento+Calcio+Perros",
		categoria: "Medicamentos",
		stock: 45,
		tags: ["perro", "calcio", "suplemento", "huesos", "dientes"],
	},
	{
		id: 1027,
		nombre: "Bebedero Automático para Perros",
		descripcion:
			"Bebedero automático para perros. Sistema de flujo constante de agua fresca. Ideal para hogares con varios perros. Fácil de montar y limpiar.",
		precio: 22000,
		imagen: "https://via.placeholder.com/150?text=Bebedero+Automático+Perros",
		categoria: "Accesorios",
		stock: 15,
		tags: ["perro", "bebedero", "automático", "agua", "fresca"],
	},
	{
		id: 1028,
		nombre: "Caja de Arena para Gatos",
		descripcion:
			"Caja de arena para gatos con borde alto. Incluye tapa para controlar olores. Fácil de limpiar y resistente a manchas. Ideal para gatos de todas las edades.",
		precio: 14000,
		imagen: "https://via.placeholder.com/150?text=Caja+Arena+Gatos",
		categoria: "Higiene",
		stock: 25,
		tags: ["gato", "caja", "arena", "control de olores", "resistente"],
	},
	{
		id: 1029,
		nombre: "Juguete de Peluche para Perro",
		descripcion:
			"Juguete de peluche para perros. Suave y duradero. Incluye sonido interior para mayor diversión. Ideal para juegos suaves y abrazos.",
		precio: 9000,
		imagen: "https://via.placeholder.com/150?text=Juguete+Peluche+Perro",
		categoria: "Juguetes",
		stock: 30,
		tags: ["perro", "juguete", "peluche", "suave", "sonido"],
	},
	{
		id: 1030,
		nombre: "Accesorios para Acuario",
		descripcion:
			"Kit de accesorios para acuarios. Incluye filtro, calentador y luces LED. Ideal para mantener el ambiente óptimo para peces. Compatible con acuarios de hasta 100 litros.",
		precio: 25000,
		imagen: "https://via.placeholder.com/150?text=Accesorios+Acuario",
		categoria: "Hábitats",
		stock: 10,
		tags: ["acuario", "accesorios", "filtro", "calentador", "luces LED"],
	},
	{
		id: 1031,
		nombre: "Alimento para Perro Senior",
		descripcion:
			"Alimento especial para perros senior. Enriquecido con antioxidantes y nutrientes para apoyar la salud en la vejez. Presentación en bolsa de 2 kg. Sabor a pavo y batata.",
		precio: 15000,
		imagen: "https://via.placeholder.com/150?text=Comida+Perro+Senior",
		categoria: "Alimentos",
		stock: 40,
		tags: ["perro", "senior", "comida", "antioxidantes", "nutrientes"],
	},
	{
		id: 1032,
		nombre: "Ropa para Perro",
		descripcion:
			"Ropa cómoda y estilizada para perros. Disponible en varios tamaños y colores. Material suave y lavable. Ideal para mantener a tu perro abrigado en climas fríos.",
		precio: 15000,
		imagen: "https://via.placeholder.com/150?text=Ropa+Perro",
		categoria: "Accesorios",
		stock: 20,
		tags: ["perro", "ropa", "cómoda", "estilizada", "abrigado"],
	},
	{
		id: 1033,
		nombre: "Comida para Gato Senior",
		descripcion:
			"Alimento especializado para gatos senior. Rico en proteínas y vitaminas esenciales para mantener la salud en la vejez. Presentación en bolsa de 1 kg. Sabor a pollo.",
		precio: 13000,
		imagen: "https://via.placeholder.com/150?text=Comida+Gato+Senior",
		categoria: "Alimentos",
		stock: 35,
		tags: ["gato", "senior", "comida", "proteínas", "vitaminas"],
	},
	{
		id: 1034,
		nombre: "Kit de Cuidado para Pequeños Mamíferos",
		descripcion:
			"Kit completo de cuidado para pequeños mamíferos. Incluye jaula, comida, bebedero y accesorios básicos. Ideal para conejos, hámsteres y cobayas.",
		precio: 30000,
		imagen: "https://via.placeholder.com/150?text=Kit+Cuidado+Mamiferos",
		categoria: "Hábitats",
		stock: 15,
		tags: ["mamíferos", "kit", "jaula", "comida", "accesorios"],
	},
	{
		id: 1035,
		nombre: "Camita para Gato",
		descripcion:
			"Camita suave y acogedora para gatos. Ideal para colocar en cualquier rincón de la casa. Material lavable y resistente. Disponible en varios colores.",
		precio: 11000,
		imagen: "https://via.placeholder.com/150?text=Camita+Gato",
		categoria: "Accesorios",
		stock: 25,
		tags: ["gato", "camita", "suave", "acogedora", "lavable"],
	},
	{
		id: 1036,
		nombre: "Comida para Perro de Razas Pequeñas",
		descripcion:
			"Alimento específico para perros de razas pequeñas. Rico en nutrientes y proteínas adaptadas. Presentación en bolsa de 1 kg. Sabor a cordero y vegetales.",
		precio: 12000,
		imagen: "https://via.placeholder.com/150?text=Comida+Perro+Razas+Pequeñas",
		categoria: "Alimentos",
		stock: 50,
		tags: ["perro", "razas pequeñas", "comida", "nutrientes", "proteínas"],
	},
	{
		id: 1037,
		nombre: "Antipulgas para Gatos",
		descripcion:
			"Tratamiento antipulgas para gatos. Eficaz contra infestaciones de pulgas. Presentación en pipetas. Seguro y fácil de aplicar.",
		precio: 9000,
		imagen: "https://via.placeholder.com/150?text=Antipulgas+Gatos",
		categoria: "Medicamentos",
		stock: 40,
		tags: ["gato", "antipulgas", "pipetas", "eficaz", "fácil de aplicar"],
	},
	{
		id: 1038,
		nombre: "Rascador con Base para Gato",
		descripcion:
			"Rascador con base robusta para gatos. Ideal para rascar y jugar. Incluye postes de sisal y juguetes colgantes. Fomenta el ejercicio y previene daños en muebles.",
		precio: 30000,
		imagen: "https://via.placeholder.com/150?text=Rascador+Base+Gato",
		categoria: "Accesorios",
		stock: 15,
		tags: ["gato", "rascador", "base", "sisal", "juguetes"],
	},
	{
		id: 1039,
		nombre: "Alimento para Perro Adulto de Razas Grandes",
		descripcion:
			"Alimento diseñado para perros adultos de razas grandes. Rico en nutrientes y proteínas específicas. Presentación en bolsa de 2 kg. Sabor a pollo y arroz.",
		precio: 16000,
		imagen: "https://via.placeholder.com/150?text=Comida+Perro+Razas+Grandes",
		categoria: "Alimentos",
		stock: 35,
		tags: ["perro", "razas grandes", "comida", "nutrientes", "proteínas"],
	},
	{
		id: 1040,
		nombre: "Acondicionador para Perros",
		descripcion:
			"Acondicionador para perros que suaviza y desenreda el pelaje. Fórmula enriquecida con vitaminas. Presentación en botella de 500 ml. Ideal para pelajes largos y rizados.",
		precio: 8000,
		imagen: "https://via.placeholder.com/150?text=Acondicionador+Perros",
		categoria: "Higiene",
		stock: 30,
		tags: ["perro", "acondicionador", "pelaje", "vitaminas", "suavizante"],
	},
	{
		id: 1041,
		nombre: "Juguete de Masticación para Perro",
		descripcion:
			"Juguete de goma resistente diseñado para la masticación intensa. Ayuda a limpiar los dientes y a mantener la mandíbula fuerte. Ideal para perros grandes.",
		precio: 12000,
		imagen: "https://via.placeholder.com/150?text=Juguete+Masticacion+Perro",
		categoria: "Juguetes",
		stock: 25,
		tags: ["perro", "juguete", "masticación", "goma", "dientes"],
	},
	{
		id: 1042,
		nombre: "Lámpara de Calor para Reptiles",
		descripcion:
			"Lámpara de calor para reptiles. Proporciona calor esencial para la digestión y bienestar de reptiles. Compatible con la mayoría de terrarios. Vida útil de 8 meses.",
		precio: 9000,
		imagen: "https://via.placeholder.com/150?text=Lámpara+Calor+Reptiles",
		categoria: "Hábitats",
		stock: 30,
		tags: ["reptiles", "lámpara", "calor", "bienestar", "terrario"],
	},
	{
		id: 1043,
		nombre: "Alimento para Pájaros Exóticos",
		descripcion:
			"Comida balanceada para pájaros exóticos. Rica en semillas y frutas. Presentación en bolsa de 1 kg. Ideal para mantener una dieta variada y saludable.",
		precio: 11000,
		imagen: "https://via.placeholder.com/150?text=Comida+Pájaros+Exóticos",
		categoria: "Alimentos",
		stock: 20,
		tags: ["pájaros", "exóticos", "comida", "semillas", "frutas"],
	},
	{
		id: 1044,
		nombre: "Rascador para Hámster",
		descripcion:
			"Rascador para hámsteres con materiales no tóxicos. Ayuda a mantener las uñas de los hámsteres recortadas y saludables. Fácil de instalar en la jaula.",
		precio: 7000,
		imagen: "https://via.placeholder.com/150?text=Rascador+Hamster",
		categoria: "Accesorios",
		stock: 25,
		tags: ["hámster", "rascador", "salud", "jaula", "no tóxico"],
	},
	{
		id: 1045,
		nombre: "Camita para Conejo",
		descripcion:
			"Camita suave y acolchada para conejos. Ideal para colocar en jaulas o áreas de descanso. Material lavable y duradero. Disponible en varios tamaños.",
		precio: 9000,
		imagen: "https://via.placeholder.com/150?text=Camita+Conejo",
		categoria: "Accesorios",
		stock: 30,
		tags: ["conejo", "camita", "suave", "acolchada", "lavable"],
	},
	{
		id: 1046,
		nombre: "Set de Cuidado de Uñas para Perro",
		descripcion:
			"Set completo para el cuidado de las uñas de perros. Incluye cortauñas y lima. Ideal para mantener las uñas recortadas y evitar problemas de salud.",
		precio: 8500,
		imagen: "https://via.placeholder.com/150?text=Set+Cuidado+Uñas+Perro",
		categoria: "Higiene",
		stock: 20,
		tags: ["perro", "cuidado", "uñas", "cortauñas", "lima"],
	},
	{
		id: 1047,
		nombre: "Caja de Arena Autolimpiante",
		descripcion:
			"Caja de arena autolimpiante para gatos. Sistema automatizado que limpia la arena y controla olores. Fácil de usar y mantener. Ideal para propietarios ocupados.",
		precio: 35000,
		imagen: "https://via.placeholder.com/150?text=Caja+Arena+Autolimpiante",
		categoria: "Higiene",
		stock: 15,
		tags: ["gato", "caja", "arena", "autolimpiante", "control de olores"],
	},
	{
		id: 1048,
		nombre: "Juguete para Pájaros con Cuerda",
		descripcion:
			"Juguete interactivo para pájaros con cuerda. Estimula la actividad física y mental. Fabricado con materiales seguros y duraderos. Ideal para jaulas de pájaros.",
		precio: 8000,
		imagen: "https://via.placeholder.com/150?text=Juguete+Pájaros+Cuerda",
		categoria: "Juguetes",
		stock: 25,
		tags: ["pájaros", "juguete", "cuerda", "interactivo", "seguro"],
	},
	{
		id: 1049,
		nombre: "Gateras de Seguridad",
		descripcion:
			"Gateras de seguridad para puertas y ventanas. Permiten el acceso controlado de gatos al exterior. Fabricadas con materiales resistentes y seguras.",
		precio: 15000,
		imagen: "https://via.placeholder.com/150?text=Gateras+Seguridad",
		categoria: "Accesorios",
		stock: 20,
		tags: ["gato", "gatera", "seguridad", "acceso", "resistente"],
	},
	{
		id: 1050,
		nombre: "Comida para Tortugas",
		descripcion:
			"Alimento especializado para tortugas. Rico en nutrientes esenciales y calcio. Presentación en bolsa de 500 g. Ideal para tortugas acuáticas y terrestres.",
		precio: 10000,
		imagen: "https://via.placeholder.com/150?text=Comida+Tortugas",
		categoria: "Alimentos",
		stock: 30,
		tags: ["tortuga", "comida", "nutrientes", "calcio", "acuario"],
	},
	{
		id: 1051,
		nombre: "Antipulgas para Perros",
		descripcion:
			"Tratamiento antipulgas para perros. Eficaz contra infestaciones de pulgas. Presentación en pipetas. Seguro y fácil de aplicar.",
		precio: 10000,
		imagen: "https://via.placeholder.com/150?text=Antipulgas+Perros",
		categoria: "Medicamentos",
		stock: 30,
		tags: ["perro", "antipulgas", "pipetas", "eficaz", "fácil de aplicar"],
	},
	{
		id: 1052,
		nombre: "Escalera para Gato",
		descripcion:
			"Escalera de varios niveles para gatos. Ideal para casas con varios niveles o áreas altas. Hecha de materiales resistentes y fácil de montar.",
		precio: 20000,
		imagen: "https://via.placeholder.com/150?text=Escalera+Gato",
		categoria: "Accesorios",
		stock: 15,
		tags: ["gato", "escalera", "varios niveles", "resistente", "montaje fácil"],
	},
];
